apiVersion: v1
kind: Service
metadata:
  name: operation-service-svc
  labels:
    app: operation-service-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30002
  selector:
    app: operation-service