apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: operation-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: operation-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70